---
title: "Code book - Getting and cleaning data project"
author: "Pepe Zamarripa"
date: "2023-05-12"
output: html_document


## Code book - Getting and celaning data project

### Dataset
The data set name is UCI HAR dataset

## Data set information
A group of thirty volunteers, aged between nineteen and fourtyeight years, participated in a series of experiments. Each individual engaged in six different activities:\
- WALKING\
- WALKING_UPSTAIRS\
- WALKING_DOWNSTAIRS\
- SITTING\
- STANDING\
- LAYING\

While wearing a Samsung Galaxy S II smartphone attached to their waist. The smartphone's embedded accelerometer and gyroscope were utilized to capture 3-axial linear acceleration and 3-axial angular velocity data at a constant rate of 50Hz. To annotate the data accurately, the experiments were video-recorded.\ 

The collected dataset was then randomly divided into two sets: 70% of the volunteers were assigned to the training data, while the remaining 30% constituted the test data.\


The signals from the sensors (accelerometer and gyroscope) underwent pre-processing, including the application of noise filters. Subsequently, the signals were sampled using fixed-width sliding windows of 2.56 seconds and a 50% overlap (128 readings per window).\ 

To differentiate between the gravitational and body motion components in the sensor acceleration signal, a Butterworth low-pass filter was utilized, resulting in the separation of body acceleration and gravity. Since the gravitational force predominantly contains low-frequency components, a filter with a cutoff frequency of 0.3 Hz was employed. From each window, a feature vector was generated by calculating various variables from both the time and frequency domains.